#include <stdlib.h>
#include <math.h>
#include <stddef.h>
#include <time.h>

#define	double	double

#define	SEQUENCES	10000000
#ifndef	RAND_MAX
#define	RAND_MAX	2147483647
#endif

/************************************

	SEQUENCES is the maximum number of random sequences
	that will be produced. A sequence changes every second


	RAND_MAX is the factor that keeps the numbers 
	between 0.0 and 1.0. If the numbers get outside
	of this interval you'll have to change RAND_MAX.

	Look in the "man random" about what is the maximum
	number generated by random() and set RAND_MAX to it


*************************************/

int	seed=3765; //for randm_() function

void	seed_()
/*
 *	Seeds the rnd_() function
 */
{
#ifdef FORTRAN
	double	r;
	randm_(&seed,&r);
#else
	srandom(time(0) % SEQUENCES);
//	srand(time(0) % SEQUENCES);
#endif
}
double	rnd_()
/*
 *	Returns a random number between 0.0 and 1.0
 */
{
#ifdef FORTRAN
	double	r;
	randm_(&seed,&r);
	return r;
#else
	return (double)random()/RAND_MAX;
//	return (double)rand()/RAND_MAX;
#endif
}
void	gaussn_(double *Y, double d, int n) 
/*	Generates an array of n random numbers with a 
 *	  Normal (Gaussian) distribution with a standard
 *	  deviation of d, and stores them in array Y.
 */
{
extern	double	gauss_(); 
	double	*x;
	for (x = Y; x - Y < n; x++)
		*x = d*gauss_();
}
double	gauss_()
/* From Numerical Recepes in C, Ch.7.2 
 * Zero mean and unit variance
 */
{
extern	double	rnd_();
	static int iset = 0;
	static double gset;
	double fac,rsq,v1,v2;
	if (iset == 0)
	{	do
		{
			v1=2.*rnd_()-1.;
			v2=2.*rnd_()-1.;
			rsq=v1*v1+v2*v2;
		}	while (rsq >= 1.0 || rsq == 0);
		fac=(double)sqrt(-2.*log(rsq)/rsq);
		gset=v1*fac;
		iset=1;
		return v2*fac;
	}
	else
	{
		iset=0;
		return gset;
	}
}
